language: java
sudo: false

jdk:
- oraclejdk8

install:

- mvn clean install -B -V

script:
- sh ./check_format.sh

after_success:
- mvn clean test cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report