# build version
version: '{build}'

# environment settings
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

platform: x64

# install required tools (java, maven)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

# Do not build on tags
skip_tags: true

# build and install artifacts
build_script:
  - mvn clean install -DskipTests

# verify artifacts
test_script:
  - mvn test

# preserve dependencies between builds
cache:
  - C:\maven\
  - C:\Users\appveyor\.m